"""Build a runnable TypeScript harness from Mastra Observational Memory 1.1.0.

The harness exposes the exact prompt builders, parsers, formatters, token
counter, and context helpers that produced Mastra's published LongMemEval
result, so ``generate.mjs`` can record their outputs as golden fixtures for
nanobot's Python port.

Usage::

    git clone --depth 1 --filter=blob:none --sparse \
        --branch @mastra/memory@1.1.0 https://github.com/mastra-ai/mastra.git mastra
    git -C mastra sparse-checkout set \
        packages/memory/src/processors/observational-memory
    python scripts/om_golden/build_harness.py \
        mastra/packages/memory/src/processors/observational-memory

The upstream files are copied unchanged except for two mechanical edits Node's
type stripping requires: relative imports gain a ``.ts`` extension, and the
engine helpers that live on the ``ObservationalMemory`` class are sliced into a
small standalone class so they can run without ``@mastra/core``.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HARNESS = HERE / "harness"

# SHA-256 of the upstream files at mastra-ai/mastra@dc7ea18 (@mastra/memory@1.1.0).
EXPECTED_SHA256 = {
    "observer-agent.ts": "c9fbd4665b010f84dc917f3a23290592b2e838063e891c0c7d2f6219567dd5ba",
    "reflector-agent.ts": "100020e969bd2a93e99c8eb4fae8f6af02c0fba43b8b7c29a7c2aa3d8b34eee1",
    "token-counter.ts": "de05bca9eb9acfdfe33ca3db7a49ca709ef917d920324c59e1e48d135ed2cab0",
    "observational-memory.ts": "081e2b2fbd18a6066059bbeb168934d7f3e6f7bb4594cc5a0b39518980d5fdd1",
}

# Class methods reused verbatim by the harness engine class.
ENGINE_METHODS = (
    "getMaxThreshold",
    "calculateDynamicThreshold",
    "shouldReflect",
    "formatObservationsForContext",
    "formatUnobservedContextBlocks",
    "representThreadIDInContext",
    "stripThreadTags",
    "wrapWithThreadTag",
    "replaceOrAppendThreadSection",
    "sortThreadsByOldestMessage",
)


def _check(source: Path) -> None:
    for name, expected in EXPECTED_SHA256.items():
        digest = hashlib.sha256((source / name).read_bytes()).hexdigest()
        if digest != expected:
            raise SystemExit(f"{name}: sha256 {digest} does not match 1.1.0 ({expected})")


def _method_source(text: str, name: str) -> str:
    """Return one class method, from its signature to its closing brace."""
    match = re.search(rf"^  private (?:async )?{name}\(", text, re.M)
    if match is None:
        raise SystemExit(f"method {name} not found")
    lines = text[match.start():].split("\n")
    body: list[str] = []
    for line in lines:
        body.append(line)
        if line == "  }":
            break
    return "\n".join(body)


def _slice_between(text: str, start_marker: str, end_marker: str) -> str:
    start = text.index(start_marker)
    end = text.index(end_marker, start)
    return text[start:end]


def build(source: Path) -> None:
    _check(source)
    HARNESS.mkdir(exist_ok=True)

    for name in ("observer-agent.ts", "reflector-agent.ts", "token-counter.ts"):
        text = (source / name).read_text(encoding="utf-8")
        text = re.sub(r"from '\./([a-z-]+)'", r"from './\1.ts'", text)
        (HARNESS / name).write_text(text, encoding="utf-8")

    engine = (source / "observational-memory.ts").read_text(encoding="utf-8")
    helpers = _slice_between(
        engine,
        "function formatRelativeTime(",
        "/**\n * Debug event emitted",
    )
    reminder = re.search(r"text: `(<system-reminder>[\s\S]*?</system-reminder>)`", engine)
    if reminder is None:
        raise SystemExit("continuation reminder not found")
    selection = _slice_between(
        engine,
        "    const threshold = this.getMaxThreshold(this.observationConfig.messageTokens);\n\n"
        "    // Calculate tokens per thread",
        "    // Debug: Log message counts per thread and date ranges",
    )
    batching = _slice_between(
        engine,
        "      const maxTokensPerBatch =",
        "      // Process batches in parallel",
    )
    methods = "\n\n".join(_method_source(engine, name) for name in ENGINE_METHODS)

    harness = f"""// Generated by build_harness.py from @mastra/memory@1.1.0. Do not edit.
import xxhash from 'xxhash-wasm';
import {{ optimizeObservationsForContext, formatMessagesForObserver }} from './observer-agent.ts';
import {{ TokenCounter }} from './token-counter.ts';

const OBSERVATIONAL_MEMORY_DEFAULTS = {{ observation: {{ maxTokensPerBatch: 10_000 }} }};

{helpers}
export {{ addRelativeTimeToObservations, formatRelativeTime }};

export const CONTINUATION_REMINDER = `{reminder.group(1)}`;

export class Engine {{
  shouldObscureThreadIds = true;
  hasher = xxhash();
  threadIdCache = new Map();
  tokenCounter = new TokenCounter();
  observationConfig: any;
  reflectionConfig: any;

  constructor(messageTokens: any = 30_000, observationTokens: any = 40_000, maxTokensPerBatch = 10_000) {{
    this.observationConfig = {{ messageTokens, maxTokensPerBatch }};
    this.reflectionConfig = {{ observationTokens }};
  }}

  selectAndBatch(messagesByThread: Map<string, any[]>) {{
{selection}
    const threadsWithMessages = new Map();
    for (const threadId of threadOrder) {{
      const msgs = messagesByThread.get(threadId);
      if (msgs && msgs.length > 0) {{
        threadsWithMessages.set(threadId, msgs);
      }}
    }}
{batching}
    return {{ threadOrder, batches: batches.map(batch => batch.threadIds) }};
  }}

{methods}
}}
"""
    (HARNESS / "engine.ts").write_text(harness, encoding="utf-8")
    print(f"harness written to {HARNESS}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    build(Path(sys.argv[1]))
